[2025-09-04T20:13:46.716-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T01:13:39.736906+00:00 [queued]>
[2025-09-04T20:13:46.719-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T01:13:39.736906+00:00 [queued]>
[2025-09-04T20:13:46.719-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-04T20:13:46.723-0500] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): check_drift> on 2025-09-05 01:13:39.736906+00:00
[2025-09-04T20:13:46.729-0500] {standard_task_runner.py:57} INFO - Started process 28405 to run task
[2025-09-04T20:13:46.731-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'movie_sentiment_retrain', 'check_drift', 'manual__2025-09-05T01:13:39.736906+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/retrain_pipeline.py', '--cfg-path', '/var/folders/q5/0d_dg10s4m55__wc3fybh0280000gr/T/tmp3yhvz4l9']
[2025-09-04T20:13:46.733-0500] {standard_task_runner.py:85} INFO - Job 71: Subtask check_drift
[2025-09-04T20:13:46.748-0500] {task_command.py:416} INFO - Running <TaskInstance: movie_sentiment_retrain.check_drift manual__2025-09-05T01:13:39.736906+00:00 [running]> on host SebastianSamay.local
[2025-09-04T20:13:46.766-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='movie_sentiment_retrain' AIRFLOW_CTX_TASK_ID='check_drift' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T01:13:39.736906+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T01:13:39.736906+00:00'
[2025-09-04T20:14:00.470-0500] {logging_mixin.py:154} INFO - Salida del monitor: Use Airflow!
reference_data_path
Datos de referencia cargados: 10000 muestras

============================================================
üìä AN√ÅLISIS DETALLADO DE DRIFT
============================================================

üéØ DATASET DRIFT:
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Porcentaje de features con drift: 50.00%
   - Features con drift: 7/8
   - Umbral configurado: 15.00%
   - ¬øSupera umbral?: S√ç ‚ö†Ô∏è

üìà DRIFT EN 'predicted_label':
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Score del test: 0.1813
   - Test estad√≠stico usado: Jensen-Shannon distance
   - P-value < 0.05: S√ç

üìà DRIFT EN 'predicted_label':
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Score del test: 0.1813
   - Test estad√≠stico usado: Jensen-Shannon distance
   - P-value < 0.05: S√ç

üéØ DATASET DRIFT:
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Porcentaje de features con drift: 50.00%
   - Features con drift: 7/8
   - Umbral configurado: 15.00%
   - ¬øSupera umbral?: S√ç ‚ö†Ô∏è

üìà DRIFT EN 'text_length':
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Score del test: 1.2650
   - Test estad√≠stico usado: Wasserstein distance (normed)
   - P-value < 0.05: S√ç

üìà DRIFT EN 'word_count':
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Score del test: 1.2963
   - Test estad√≠stico usado: Wasserstein distance (normed)
   - P-value < 0.05: S√ç

üìà DRIFT EN 'max_probability':
   - Drift detectado: S√ç ‚ö†Ô∏è
   - Score del test: 0.2142
   - Test estad√≠stico usado: Wasserstein distance (normed)
   - P-value < 0.05: S√ç

üìä COMPARACI√ìN DE DISTRIBUCIONES:
   Referencia (n=10000)
   - Predicciones positivas: 50.38%
   - Confianza promedio: 0.845
   - Longitud promedio texto: 1305

   Producci√≥n (n=8)
   - Predicciones positivas: 75.00%
   - Confianza promedio: 0.835
   - Longitud promedio texto: 44
‚úì Reporte de drift guardado en: monitoring_data/drift_report_20250904_201359.html
‚ö†Ô∏è  ALERTA: Se detect√≥ drift significativo. Reentrenamiento recomendado.
  - Dataset drift: 50.00%
  - Prediction drift: False
  - Confidence drift: True
[2025-09-04T20:14:00.472-0500] {logging_mixin.py:154} INFO - Errores: /Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/venv_mlops/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/monitoring/drift_monitor.py", line 529, in <module>
    needs_retrain = check_drift_for_airflow()
  File "/Users/sebatiancarvalho/Desktop/Repositorios/SCSProjects/movie-sentiment-mlops-V3/monitoring/drift_monitor.py", line 511, in check_drift_for_airflow
    json.dump(result, f)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bool_ is not JSON serializable
[2025-09-04T20:14:00.472-0500] {logging_mixin.py:154} INFO - Error verificando drift: Expecting value: line 1 column 113 (char 112)
[2025-09-04T20:14:00.473-0500] {python.py:194} INFO - Done. Returned value was: skip_retrain
[2025-09-04T20:14:00.473-0500] {python.py:227} INFO - Branch callable return skip_retrain
[2025-09-04T20:14:00.473-0500] {skipmixin.py:173} INFO - Following branch skip_retrain
[2025-09-04T20:14:00.477-0500] {skipmixin.py:239} INFO - Skipping tasks [('retrain_model', -1)]
[2025-09-04T20:14:00.487-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=movie_sentiment_retrain, task_id=check_drift, execution_date=20250905T011339, start_date=20250905T011346, end_date=20250905T011400
[2025-09-04T20:14:00.514-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-04T20:14:00.524-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
